version: '3.8'
services:
  notification-service:
    container_name: notification-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: on-failure